apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website-monitor
  template:
    metadata:
      labels:
        app: website-monitor
    spec:
      containers:
      - name: website-monitor
        image: website-monitor:latest
        imagePullPolicy: Never
        env:
        - name: SITES
          value: "https://google.com,https://github.com,https://abcxyz123.com"
